config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:show,:index,:edit,:update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follower', as: 'follows'
  	get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  get 'search/search'
  root 'home#top'
  get 'home/about'
end

app/models/user.rb
class User < ApplicationRecord
  include JpPrefecture

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
  jp_prefecture :prefecture_code

  attachment :profile_image, destroy: false

  has_many :books,dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name,presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  def User.search(content, model, how)
      if how == 'match'
        User.where(name: content)
      elsif how  == 'foward'
        User.where("name LIKE?", "#{content}%")
      elsif how == 'backward'
        User.where("name LIKE?", "%#{content}")
      elsif how == 'partical'
        User.where("name LIKE?", "%#{content}%")
      else
        User.all
      end
  end

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def follow(user_id)
  	follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
  	follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
  	following_user.include?(user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     build_resource(sign_up_params)
    resource.save
    NotificationMailer.send_confirm_to_user(resource).deliver

    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update]
  before_action :screen_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end
  def screen_user
    if params[:id].to_i != current_user.id
      redirect_to user_path(current_user)
    end
  end
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  def followed
    @user = User.find(params[:id])
    @users = @user.followed
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% users.each do |user| %>
<tr>
	<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
	</td>
	<td><%= user.name %>
	<td>フォロー数：<%= user.following_user.count %>
	</td>
	<td>フォロワー数：<%= user.follower_user.count %>
	</td>
	<td>					
	<% if current_user != user %>
		<% if current_user.following?(user) %>
			<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
		<% else %>
			<%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
		<% end %>
	<% end %>
	</td>
	<td><%= link_to "Show", user_path(user) %>
	</td>
</tr>

<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", class: "image") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
		    <th>follows</th>
		    <th><%= link_to user.follower.count, user_follows_path(user) %></th>
		 </tr>
		 <tr>
		    <th>followers</th>
		    <th><%= link_to user.followed.count, user_followers_path(user) %></th>
	  	 </tr>
	  	</table>
	  	<% if current_user != user %>
			<% if current_user.following?(user) %>
				<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
			<% else %>
				<%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
			<% end %>
		<% end %>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class="box">
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<h3><%= @user.errors.count %> error occurrence</h3><!--エラーメッセ-->
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>
</div>

app/views/users/index.html.erb
 <div class="container">
 	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>
		<div class="col-xs-9">

		<h2>Users</h2>
<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td>フォロー数：<%= user.following_user.count %>
						</td>
						<td>フォロワー数：<%= user.follower_user.count %>
						</td>
						<td>					
						<% if current_user != user %>
							<% if current_user.following?(user) %>
								<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
							<% else %>
								<%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
							<% end %>
						<% end %>
						</td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

			<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
		</div>
		<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
					<th>Opinion</th>
			<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to (book.user) do %>
					<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
				<td><%= book.body %></td>
			</tr>
			<% end %>
		</tbody>
		</table>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
<% if current_user == @user %>
<h2>Your Map</h2>

<div id='map' data-latitude="<%= @user.latitude %>" data-longitude="<%= @user.longitude %>" data-address="<%= @user.city %>"></div>

<!-- buttonをクリックしたらcodeAddressを実行　-->
<style>
#map{
  height: 400px;
}
</style>

<script>
/*
mapを関数の外で定義(codeAddressでも使うため)
geocoderを用意
*/



let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()
    let inputAddress = document.getElementById('map').getAttribute('data-address');

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
  let latitude = parseFloat(document.getElementById('map').getAttribute('data-latitude'))
  let longitude = parseFloat(document.getElementById('map').getAttribute('data-longitude'))
  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: latitude, lng: longitude},
  zoom: 8
  });
}

function codeAddress(){
  // 入力を取得

}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['KEY']%>&callback=initMap" async defer></script>
<% end %>
</div>
</div>
<!--books一覧 -->