config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:show,:index,:edit,:update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follower', as: 'follows'
  	get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  get 'search/search'
  root 'home#top'
  get 'home/about'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	def Book.search(content, model, how)
  		if how == 'match'
  			Book.where(title: content, body: content)
  		elsif how  == 'foward'
  			Book.where("title LIKE?", "#{content}%")
  		elsif how == 'backward'
  			Book.where("title LIKE?", "%#{content}")
  		elsif how == 'partical'
  			Book.where("title LIKE?", "%#{content}%")
  		else
  			Book.all
  		end
  end
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_book, only: [:update, :edit]
  def show
  	@bookd = Book.find(params[:id])
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
    @book_book_comments = @bookd.book_comments
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
    @user = current_user
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		 redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
      @user = current_user
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end
  def screen_book
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
 			<% end %>
        </ul>
<% end %>
<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
		<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>
						<%= render 'favorites/favorite',book: book %>
						</td>
						<td>
							<p>コメント数：
						<%= book.book_comments.count %></p>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

		<!--books一覧 -->


		</div>
	</div>
</div>	

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform' %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						
						<%= attachment_image_tag(@bookd.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= link_to @bookd.user.name, user_path(@bookd.user) %>
					
					</td>
					<td><%= link_to @bookd.title, @book %></td>
					<td><%= @bookd.body %></td>
					<td>
						<%= render 'favorites/favorite', book: @bookd %>
					</td>

					<td>
						<p>コメント数：
						<%= @bookd.book_comments.count %></p>
					</td>
					<% if @bookd.user_id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@bookd), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",book_path, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<div class="comment_area">
				<%= render 'book_comments/form', comment: @book_comment, book: @bookd %>
				<%= render 'book_comments/comment', comments: @bookd.book_comments %>
			</div>
	</div>
	</div>
</div>